// Generated by scripts/prepare-icons.mjs.
export const icons: Record<string, { path: string; width: number; height: number }> = {
  "yieldloop-wafer-triage-with-HIL": {
    "path": "images/icons/yieldloop-wafer-triage-with-HIL.webp",
    "width": 560,
    "height": 560
  },
  "enterprise-rag-aws": {
    "path": "images/icons/enterprise-rag-aws.webp",
    "width": 560,
    "height": 560
  },
  "edge-ai-inspection-gates": {
    "path": "images/icons/edge-ai-inspection-gates.webp",
    "width": 560,
    "height": 560
  },
  "sentinel-ai": {
    "path": "images/icons/sentinel-ai.webp",
    "width": 560,
    "height": 560
  },
  "fault-triage-ai": {
    "path": "images/icons/fault-triage-ai.webp",
    "width": 560,
    "height": 560
  },
  "mlx-sft-pubmedqa": {
    "path": "images/icons/mlx-sft-pubmedqa.webp",
    "width": 560,
    "height": 560
  },
  "linegate": {
    "path": "images/icons/linegate.webp",
    "width": 560,
    "height": 560
  },
  "agent-org-chart": {
    "path": "images/icons/agent-org-chart.webp",
    "width": 560,
    "height": 560
  },
  "langgraph_data_analytics_agents": {
    "path": "images/icons/langgraph_data_analytics_agents.webp",
    "width": 560,
    "height": 560
  },
  "reinforcement_learning_based_pump_control_with_edge_deployment": {
    "path": "images/icons/reinforcement_learning_based_pump_control_with_edge_deployment.webp",
    "width": 560,
    "height": 560
  },
  "jev-test-confidence-gate": {
    "path": "images/icons/jev-test-confidence-gate.webp",
    "width": 560,
    "height": 560
  },
  "docu_scribe_ai": {
    "path": "images/icons/docu_scribe_ai.webp",
    "width": 560,
    "height": 560
  },
  "Rag_with_knowledge_graph_neo4j": {
    "path": "images/icons/Rag_with_knowledge_graph_neo4j.webp",
    "width": 560,
    "height": 560
  },
  "colpali_rag": {
    "path": "images/icons/colpali_rag.webp",
    "width": 560,
    "height": 560
  },
  "financial_doc_analyser": {
    "path": "images/icons/financial_doc_analyser.webp",
    "width": 560,
    "height": 560
  },
  "agentic-memory-patterns": {
    "path": "images/icons/agentic-memory-patterns.webp",
    "width": 560,
    "height": 560
  },
  "machine-failure-api-aws-ECR": {
    "path": "images/icons/machine-failure-api-aws-ECR.webp",
    "width": 560,
    "height": 560
  },
  "llama-2_fine_tune_AWS_deploy": {
    "path": "images/icons/llama-2_fine_tune_AWS_deploy.webp",
    "width": 560,
    "height": 560
  }
};
