// Publishes generated project icons: trims each source's empty margin, re-centers it at a common scale,
// writes a WebP to public/images/icons, and records provenance and output hashes.
import sharp from 'sharp';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';

const MANIFEST = 'docs/portfolio/generated-icons.json';
const SIZE = 560; // output square, px
const FILL = 0.72; // share of the square the trimmed object may occupy

const sha = (bytes) => crypto.createHash('sha256').update(bytes).digest('hex');
const entries = JSON.parse(await fs.readFile(MANIFEST, 'utf8'));
await fs.mkdir('public/images/icons', { recursive: true });

for (const entry of entries) {
  const input = await fs.readFile(entry.file);
  // Snap the model's near-white backdrop to pure white so it disappears under mix-blend-mode: multiply.
  const { data, info } = await sharp(input).flatten({ background: '#ffffff' }).raw().toBuffer({ resolveWithObject: true });
  for (let i = 0; i < data.length; i += info.channels) {
    if (data[i] > 236 && data[i + 1] > 236 && data[i + 2] > 236) data[i] = data[i + 1] = data[i + 2] = 255;
  }
  const cleaned = await sharp(data, { raw: info }).png().toBuffer();
  const object = await sharp(cleaned).trim({ background: '#ffffff', threshold: 18 }).toBuffer();
  const box = Math.round(SIZE * FILL);
  const fitted = await sharp(object).resize({ width: box, height: box, fit: 'inside' }).toBuffer();
  const path = `images/icons/${entry.slug}.webp`;
  await sharp({ create: { width: SIZE, height: SIZE, channels: 3, background: '#ffffff' } })
    .composite([{ input: fitted, gravity: 'centre' }])
    .webp({ quality: 84 })
    .toFile(`public/${path}`);
  const bytes = await fs.readFile(`public/${path}`);
  Object.assign(entry, {
    sourceHash: sha(input),
    rights: 'Generated for the owner with Recraft V4.1 via the Higgsfield API; illustrative icon, not a project artifact.',
    processing: `Near-white backdrop (>236) snapped to white, trimmed white margin, fitted to ${Math.round(FILL * 100)}% of a ${SIZE}px white square, WebP quality 84.`,
    output: { path, width: SIZE, height: SIZE, format: 'webp', bytes: bytes.length, sha256: sha(bytes) },
  });
}

await fs.writeFile(MANIFEST, `${JSON.stringify(entries, null, 2)}\n`);
await fs.writeFile(
  'src/content/icons.ts',
  '// Generated by scripts/prepare-icons.mjs.\nexport const icons: Record<string, { path: string; width: number; height: number }> = ' +
    JSON.stringify(Object.fromEntries(entries.map((e) => [e.slug, { path: e.output.path, width: e.output.width, height: e.output.height }])), null, 2) +
    ';\n',
);
console.log(`Prepared ${entries.length} icons`);
