import sharp from 'sharp';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import path from 'node:path';
const sources = JSON.parse(await fs.readFile('docs/portfolio/asset-sources.json', 'utf8'));
const records = [];
for (const s of sources) {
  const response = await fetch(s.sourceUrl);
  if (!response.ok) throw new Error(`${response.status} ${s.sourceUrl}`);
  const input = Buffer.from(await response.arrayBuffer());
  const sourceHash = crypto.createHash('sha256').update(input).digest('hex');
  const base = `images/${s.id === 'portrait' ? 'profile' : `projects/${s.project}`}/${s.id}`;
  const outputs = [];
  for (const [suffix, width, quality] of [['card', 780, 85], ['full', 1920, 92]]) {
    const localPath = `${base}-${suffix}.webp`;
    await fs.mkdir(path.dirname(`public/${localPath}`), { recursive: true });
    await sharp(input).rotate().resize({ width, withoutEnlargement: true }).webp({ quality }).toFile(`public/${localPath}`);
    const bytes = await fs.readFile(`public/${localPath}`);
    const m = await sharp(bytes).metadata();
    outputs.push({ path: localPath, width: m.width, height: m.height, format: m.format, bytes: bytes.length, sha256: crypto.createHash('sha256').update(bytes).digest('hex') });
  }
  records.push({ ...s, sourceHash, outputs, processing: 'EXIF orientation applied; proportional resize, no crop; WebP quality 85/92; source pixels otherwise unchanged.', usage: s.id === 'portrait' ? ['hero','social'] : ['project card','case study','full-size viewer'] });
}
await fs.writeFile('docs/portfolio/assets.json', JSON.stringify(records, null, 2)+'\n');
await fs.mkdir('src/content', {recursive:true});
await fs.writeFile('src/content/assets.ts', '// Generated by scripts/prepare-assets.mjs.\nexport const assets = '+JSON.stringify(records.map(s=>({id:s.id,alt:s.alt,caption:s.caption,attribution:s.attribution,sourceUrl:s.sourceUrl,outputs:s.outputs})),null,2)+' as const;\nexport const getAsset = (id: string) => { const asset = assets.find(a => a.id === id); if (!asset) throw new Error(`Unknown asset: ${id}`); return asset; };\n');
console.log(`Prepared ${records.length} verified source images`);
