import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const browser=await chromium.launch({channel:'chrome'});const page=await browser.newPage({viewport:{width:1200,height:630},deviceScaleFactor:1});
const manifest=JSON.parse(await fs.readFile('docs/portfolio/assets.json','utf8'));
const data=async id=>'data:image/webp;base64,'+(await fs.readFile('public/'+manifest.find(a=>a.id===id).outputs[0].path)).toString('base64');
await page.setContent(`<html lang="en"><head><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#013e5b;color:#fff;font-family:Arial,sans-serif;padding:48px 60px;width:1200px;height:630px}.top{display:flex;justify-content:space-between;font-size:17px;border-bottom:1px solid rgba(255,255,255,.3);padding-bottom:20px}.top span{color:#a3e6ff}.body{display:flex;justify-content:space-between;align-items:center;padding-top:38px}h1{font-size:57px;letter-spacing:-2px;line-height:1.1;font-weight:550;margin:0 0 22px;max-width:800px}h1 span{color:#a3e6ff}p{font-size:18px;line-height:1.7;color:#b6c0c1;margin:0}.portrait{width:180px;border-radius:6px;border:8px solid #fff}.bottom{display:flex;gap:16px;align-items:center;margin-top:35px}.evidence{background:#eef9ff;border:3px solid #2794f1;width:185px;height:108px;padding:8px;object-fit:contain}.label{margin-left:10px;font-size:16px;color:#a3e6ff;line-height:1.8}</style></head><body><div class="top"><strong>Abhishek Shah</strong><span>BEAVERTON, OREGON / SELECTED WORK</span></div><div class="body"><div><h1>AI Architect &amp;<br><span>Technical Program<br>Manager</span></h1><p>Enterprise AI. Industrial ML. Reliable agent systems.</p></div><img class="portrait" src="${await data('portrait')}" alt="Portrait of Abhishek Shah"></div><div class="bottom"><img class="evidence" src="${await data('rag-system')}" alt="AWS architecture"><img class="evidence" src="${await data('mlx-accuracy')}" alt="Recorded model evaluation"><div class="label">Real artifacts. Explicit boundaries.<br>Evidence you can inspect.</div></div></body></html>`);
await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.screenshot({path:'public/images/social/portfolio.png'});await browser.close();
for(const [id,file,width,height,format] of [['social-card','portfolio.png',1200,630,'png'],['favicon','favicon.svg',64,64,'svg']]){
 const buffer=await fs.readFile('public/images/social/'+file);const record={id,sourceRepository:'abhishek-shah-portfolio',sourceSha:null,sourcePath:'scripts/social-card.mjs',sourceUrl:null,sourceHash:crypto.createHash('sha256').update(await fs.readFile(id==='social-card'?'scripts/social-card.mjs':'public/images/social/favicon.svg')).digest('hex'),rights:'Original portfolio typography/layout. Social card includes owner-authorized portrait and source artifacts; input provenance retained in assets.json.',attribution:'Abhishek Shah',alt:id==='favicon'?'AS monogram':'Abhishek Shah, AI Architect & Technical Program Manager, portrait and project evidence.',caption:'Portfolio identity',usage:[id==='favicon'?'favicon':'social sharing'],processing:'Social card is a browser-rendered typographic layout; favicon is static text SVG. No retouching.',inputs:id==='social-card'?['portrait','rag-system','mlx-accuracy']:[],outputs:[{path:'images/social/'+file,width,height,format,bytes:buffer.length,sha256:crypto.createHash('sha256').update(buffer).digest('hex')}]};
 const index=manifest.findIndex(r=>r.id===id);if(index<0)manifest.push(record);else manifest[index]=record;
}
await fs.writeFile('docs/portfolio/assets.json',JSON.stringify(manifest,null,2)+'\n');console.log('Rendered social card and recorded generated asset provenance');
